import Head from 'next/head';
import Hero from '@/components/Hero';
import Slider from '@/components/Slider';
import { sliderData } from '@/constants';
import Instagram from '@/components/Instagram';

export default function Home(): JSX.Element {
  return (
    <>
      <Head>
        <title>Captur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero
        heading="Captur Photography"
        message="I capture moments in nature and keep them alive."
      />
      <Slider slides={sliderData} />
      <Instagram />
    </>
  );
}
